#!/usr/bin/env python3
"""
One-time setup script to create ~/.Xauthority for XWayland on Wayland/Hyprland.

PyAutoGUI depends on python-xlib, which requires an X11 authentication cookie
to connect. On Wayland with XWayland, this file is typically auto-generated by
the desktop session — but in minimal setups (e.g., Hyprland), it may be missing.

Run this once, then run the bot as normal.
"""

import os
import struct
import sys


def create_xauthority(display=":0"):
    home = os.path.expanduser("~")
    path = os.path.join(home, ".Xauthority")

    if os.path.exists(path):
        print(f"File already exists: {path}")
        return

    cookie = os.urandom(16)
    with open(path, "wb") as f:
        # FamilyLocal (256), empty host, display, 'MIT-MAGIC-COOKIE-1', cookie
        f.write(struct.pack(">H", 256))        # family
        f.write(struct.pack(">H", 0))          # host len
        f.write(b"")                            # host
        f.write(struct.pack(">H", len(display)))  # display len
        f.write(display.encode())               # display
        f.write(struct.pack(">H", len("MIT-MAGIC-COOKIE-1")))  # name len
        f.write(b"MIT-MAGIC-COOKIE-1")          # name
        f.write(struct.pack(">H", len(cookie)))  # data len
        f.write(cookie)                         # cookie

    print(f"Created: {path}")


def test_pyautogui():
    try:
        import pyautogui
        width, height = pyautogui.size()
        print(f"PyAutoGUI connected successfully. Screen size: {width}x{height}")
        return True
    except Exception as e:
        print(f"PyAutoGUI failed: {e}")
        return False


if __name__ == "__main__":
    create_xauthority(display=os.environ.get("DISPLAY", ":0"))
    print("\nTesting PyAutoGUI...")
    if test_pyautogui():
        print("\n✅ Setup complete. You can now run the bot.")
        sys.exit(0)
    else:
        print("\n❌ Setup incomplete. See error above.")
        sys.exit(1)
